feat: Add workflow to bump and tag dev
eclipse-zenoh/ci pull request #157
Opened 2024-06-10 14:40 UTC by diogomatsubara

Once we make a release, we can open the new development line. This workflow helps facilitate that.

2024-06-10 14:43 UTC, fuzzypixelz reviewed
Tags cannot be merged via pull requests. They need to be pushed directly into a branch.

2024-06-10 15:21 UTC, fuzzypixelz requested changes

2024-06-10 15:21 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +name: Bump and tag dev branch
```suggestion
name: Bump and tag branch 
```

Can be any branch.

2024-06-10 15:21 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +      version:
I think we would like to customize the target branch here (e.g. `main` vs `dev/*`).

2024-06-10 15:21 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +    runs-on: [self-hosted, ubuntu-22.04]
When ready to merge, this ought to be changed to `ubuntu-latest`.

2024-06-10 15:21 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +      - uses: eclipse-zenoh/ci/.github/workflows/branch-bump-tag-crates.yml@main
This workflow, in addition to calling `bump-crates`, will call `create-release-branch` (e.g. `release/0.11.1-dev`). This is not what we want. We only need to call `bump-crates`.

2024-06-10 15:21 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +      - name: Create pull request version change
The `bump-crates` action (and the `branch-bump-tag-crates` workflow for that matter) push changes directly into the repository. This pull request wouldn't achieve anything.

2024-06-10 15:21 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +      - name: Create pull request version change
Similar to the above, the `bump-and-tag.bash` script pushes the version changes and the tag directly to the repository. The pull request doesn't achieve anything.

2024-06-10 15:25 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +    runs-on: [self-hosted, ubuntu-22.04]
When ready to merge, this ought to be changed to `ubuntu-latest`.

2024-06-11 10:40 UTC, diogomatsubara commented on .github/workflows/bump-tag-dev.yml
> +name: Bump and tag dev branch
I wanted to make it clear that this workflow is to open a new development line. Fixed as you suggested.

2024-06-11 10:49 UTC, diogomatsubara commented on .github/workflows/bump-tag-dev.yml
> +      - uses: eclipse-zenoh/ci/.github/workflows/branch-bump-tag-crates.yml@main
It'll create `release/dry-run/0.11.1-dev` with the version changes and that commit tagged to `0.11.1-dev`, on the subsequent step, we use the same branch to create the PR against main with the version changes. We don't want to force push any changes directly to main like we do with the release branch. That's why this workflow has an additional step to PR the changes.

2024-06-11 10:49 UTC, diogomatsubara commented on .github/workflows/bump-tag-dev.yml
> +      - name: Create pull request version change
We don't want to push things directly to main. We want to make the version changes as a PR. What we force push is the tag to the repo.

2024-06-11 10:49 UTC, diogomatsubara commented on .github/workflows/bump-tag-dev.yml
> +      version:
Can you elaborate on how this would work with `dev/*` branches vs `main`? My thought here is that this workflow would always branch from main, make the version changes in the Cargo.toml files and PR the changes back to main, thus not requiring a branch input.

2024-06-12 08:09 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +      version:
I misunderstood. The only problem with this is that the branch will be named `release/0.11.1-dev`. Which is quite a misleading name.

2024-06-13 16:38 UTC, diogomatsubara commented on .github/workflows/bump-tag-dev.yml
> +      version:
TBH, I don't mind the misleading name, the branch is just a temporary branch used to merge the version changes and should be deleted after the PR is merged. It can be fixed though on a subsequent PR.

2024-07-03 16:11 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +          bump-deps-pattern: 'zenoh.*'
What this will do is bump all dependencies to `input.version` and remove the `git` and `branch` fields. This is because leaving the `release/X.Y.Z` was causing issues with crates.io publication (CI would pass because it was using the branch, but cargo-publish would fail because it uses crates.io).

See: https://github.com/eclipse-zenoh/ci/blob/main/src/cargo.ts#L188.

So the action needs to be updated to allow for either (1) deleting the branch field, (2) changing the branch field or (3) keeping it as is.

Once that is done the branch would kept as is (i.e. `main`) or removed altogether (to use the default branch, as `main` is redundant).

2024-07-03 16:11 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +name: Bump and tag branch
```suggestion
name: Bump and tag dev version
```

2024-07-03 16:11 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +    runs-on: [ubuntu-latest]
```suggestion
    runs-on: ubuntu-latest
```

2024-07-03 16:11 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +    runs-on: [ubuntu-latest]
```suggestion
    runs-on: ubuntu-latest
```

2024-07-03 16:11 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +          BUMP_DEPS_VERSION: ${{ inputs.version }}
The `bump-and-tag.bash` scripts don't have the same issue as the `bump-crates` action. The branch would not be deleted.

2024-07-03 16:11 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +          title: Bump dev version to ${{ inputs.version }}`
```suggestion
          title: Bump dev version to `${{ inputs.version }}`
```

2024-07-03 16:11 UTC, fuzzypixelz commented on .github/workflows/bump-tag-dev.yml
> +          commit-message: "build: Bump dev version"
```suggestion
          commit-message: "chore: Bump dev version to `${{ input.version }}`"
```

2024-07-03 16:36 UTC, diogomatsubara commented on .github/workflows/bump-tag-dev.yml
> +          bump-deps-pattern: 'zenoh.*'
The branch parameter here is used for `git clone` the correct branch for our modifications, created in the previous step with create-release-branch action. It's not the branch passed on to `cargo.bumpDependencies` through the `inputs.bumpDepsBranch`

2024-07-03 16:51 UTC, diogomatsubara commented on .github/workflows/bump-tag-dev.yml
> +          BUMP_DEPS_VERSION: ${{ inputs.version }}
Why do we care? A PR will be created and the branch can be deleted after the PR is merged.

2024-07-04 07:53 UTC, diogomatsubara commented
I tried this one out in a private branch and it failed. I'll go back to the drawing board.

2024-07-04 07:53 UTC, closed without merging