fix: allow install cargo package from git
eclipse-zenoh/ci pull request #219
Opened 2024-09-17 16:16 UTC by diogomatsubara

Add option to installBinaryCached to install from git which allows installing estuary from our fork.

2024-09-18 15:31 UTC, fuzzypixelz requested changes
All dependencies are stored in `ci.config.json`, I would do something like this:

```
{
  "git": {
    "user": {
      "name": "eclipse-zenoh-bot",
      "email": "eclipse-zenoh-bot@users.noreply.github.com"
    }
  },
  "lock": {
    "cratesio": {
      "cargo-deb": "2.1.0",
      "estuary": "0.1.1",
      "cross": "0.2.5",
      "toml-cli2": "0.3.2"
    },
    "git": {
      "estuary": {
        "url": "...",
        "branch": "..."
      } 
    }
  }
}
```

2024-09-20 10:36 UTC, fuzzypixelz requested changes

2024-09-20 10:36 UTC, fuzzypixelz commented on src/config.ts
> +      };
```suggestion
      [key: string]: string;
```

2024-09-20 10:36 UTC, fuzzypixelz commented on src/estuary.ts
> +  await cargo.installBinaryCached(name, {
There should be another function `cargo.installBinaryFromGit` because this one gets the crate version from `config.lock.cratesio` and tries to cache it:

https://github.com/eclipse-zenoh/ci/blob/79f662a25c46b45eff72382328a94d2b304713f2/src/cargo.ts#L290-L294

Which will make `CargoInstallOptions` unneeded.

If we want to maintain the caching functionality then we should use a `rev` instead of `branch` because something like `main` is a moving target. The caching key will also need a `-git`/`-cratesio` suffix to indicate the package source.

2024-09-23 10:28 UTC, fuzzypixelz commented on ci.config.json
> +        "url": "https://github.com/fuzzypixelz/estuary.git",
```suggestion
        "url": "https://github.com/ZettaScaleLabs/estuary.git",
```

I added a fork under ZettaScaleLabs so we don't have to rely on my private account 🙃

2024-09-23 10:28 UTC, fuzzypixelz commented on src/config.ts
> +        [key: string]: string;
Any reason for keeping this generic instead of `{ url: string, branch: string }`?

2024-09-23 11:08 UTC, diogomatsubara commented on src/config.ts
> +        [key: string]: string;
I was following your suggestion in the previous review

2024-09-23 11:12 UTC, diogomatsubara commented on src/config.ts
> +        [key: string]: string;
Fixed.

2024-09-23 11:50 UTC, merged